### ISSUE TITLE
Plugin ServerMail error!

### ISSUE THREAD

**Issue by OwnerSCIFahrul** [popkechupki/ServerMail#4]
21:15:51 [INFO ] Enabling ServerMail v1.0.2
21:15:51 [ERROR] Throwing
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access method org.sqlite.core.DB.bind_parameter_count(J)I from class org.sqlite.core.CorePreparedStatement
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [minecraft_server.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:746) [minecraft_server.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:735) [minecraft_server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:571) [minecraft_server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [minecraft_server.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access method org.sqlite.core.DB.bind_parameter_count(J)I from class org.sqlite.core.CorePreparedStatement
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:50) ~[?:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[?:?]
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[?:?]
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[?:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[?:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[?:?]
        at net.comorevi.np.sma.util.DataProvider.connectSQL(DataProvider.java:150) ~[?:?]
        at net.comorevi.np.sma.ServerMailPlugin.onEnable(ServerMailPlugin.java:21) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[minecraft_server.jar:?]
        ... 4 more
21:15:51 [INFO ] Disabling ServerMail v1.0.2

**Comment by popkechupki** [comment]
Try latest version. In my environment, there is no problem.

**Comment by OwnerSCIFahrul** [comment]
can you give me the jar plugin to work with nukkit 1.0 for me?

**Comment by popkechupki** [comment]
See Release or Cloudburst Forum.
